import random

initial_readers = ["Katinėlis Pūkuotukas",
"Aš Pats Nesuprantu",
"Pūkuotas Dramblys",
"Šokantis Pyragas",
"Raudonas Bananų Pats",
"Burbulinis Šuo",
"Saldus Sūrio Sūris",
"Džiaugsminga Laužyta Banga",
"Kaimo Tinginys",
"Mėnulio Kepurė",
"Juokingas Varlė",
"Įsikūnijęs Žirafa",
"Nežinomas Krapukas",
"Šokoladinis Tinginys",
"Kiaušinis Balansavimas",
"Slaptoji Pica",
"Skraidantis Batutas",
"Karamelinis Foka",
"Dainuojantis Paukštis",
"Pūkų Svajotojas",
"Tingus Panda",
"Burbuliuojantis Pienas",
"Vytis Vakarėlis",
"Šluota Vajus",
"Palaidinukas Smaližius",
"Pusryčių Miegalius",
"Jautis Su Kepurė",
"Panašus Į Pusryčius",
"Juokingas Kepurinis",
"Šokantis Vyras",
"Pavasarinis Drakonas",
"Sklandus Bananų Ritinys",
"Kreminis Lazdynas",
"Žaismingas Pupeliukas",
"Valgomasis Vėžlys",
"Sūrus Avokadas",
"Įspūdingas Kiškis",
"Juokingas Pilkas Debesėlis",
"Mielas Avinas",
"Šokinėjantis Žirgas",
"Nupieštas Kepurinis",
"Balionų Pasaka",
"Mėlynas Giraffas",
"Akrobatinis Kiaušinis",
"Šventinis Pyragėlis",
"Naktinis Sūriukas",
"Žalias Tinginys",
"Džiugus Džemperis",
"Keistas Moliūgas",
"Saldus Žirafas"]

initial_book_names = [
"Ugnies Žiedas",
"Vėjo Dainos",
"Laiko Sūkuriai",
"Paslaptis",
"Paskutinė Mūza",
"Nakties Sūkurys",
"Šviesos Kelias",
"Dangaus Vaikai",
"Pavasario Pėdsakai",
"Žvaigždžių Kelionė",
"Rudens Pasaka",
"Žalioji Rūta",
"Nekaltoji Meilė",
"Vampyro Vakaras",
"Vėjo Šokis",
"Mirusiųjų Naktis",
"Saldūs Sapnai",
"Dulkių Jūra",
"Nematomas Draugas",
"Naktinė Medžioklė",
"Vandenyno Paslaptys",
"Lauko Giesmė",
"Knygų Šalis",
"Magijos Aidas",
"Dvasios Kova",
"Kalnų Pėdsakai",
"Sparnuota Širdis",
"Saulės Mūša",
"Ledinė Srovė",
"Šešėlių Vakaras",
"Akmenų Pasaka",
"Vilties Keliu",
"Vandens Kelias",
"Širdies Pavasaris",
"Nemirtingas Meilė",
"Senas Draugas",
"Tamsos Pasaka",
"Pavasario Atgimimas",
"Išminties Žodis",
"Kraujas ir Sniegas",
"Skrydžio Tiesa",
"Burtininkų Kova",
"Atgimimo Laikas",
"Bjaurusis Ančiukas",
"Žemės Sūnus",
"Kalbantis Miškas",
"Žvaigždžių Dulkės",
"Dangaus Kelyje",
"Svetimas Žemėje",
"Apsiniaukusi Naktis"
]

initial_authors = [
"Julius Matusas",
"Gabija Raudonė",
"Mantas Petkevičius",
"Eglė Vaitkienė",
"Raimondas Šuminas",
"Aistė Malinauskaitė",
"Tomas Lukoševičius",
"Viktorija Žemaitė",
"Dainius Šuminas",
"Laura Kučinskaitė",
"Andrius Vaitkus",
"Giedrė Šulskytė",
"Raimonda Giedraitytė",
"Darius Sokolovas",
"Vaida Žygimantaitė",
"Arminas Karpavičius",
"Kotryna Marija",
"Valdas Krivickas",
"Inga Aleknavičiūtė",
"Simonas Šapoka",
"Neringa Žilinskaitė",
"Darius Malūnas",
"Justas Švėgžda",
"Gintarė Giedrė",
"Jolanta Vasilevskaitė",
"Aurelijus Jankauskas",
"Rūta Žiemelė",
"Vaidotas Laužikas",
"Miglė Karpova",
"Saulius Rutkauskas",
"Gabrielė Širinskaitė",
"Andrius Alekna",
"Julija Kuprijanova",
"Vytautas Krivickas",
"Rasa Pienkaitė",
"Raimundas Žukauskas",
"Marija Rimkuvienė",
"Martynas Černiauskas",
"Simona Burokaitė",
"Kęstutis Rimeikis",
"Neringa Vėlyvytė",
"Tomas Janavičius",
"Dainius Urbonas",
"Agnė Karpavičiūtė",
"Vytas Noreika",
"Kristina Paliulytė",
"Darius Paulauskas",
"Mantas Pavilonis",
"Evelina Jančiauskaitė",
"Vėjas Šiaurinis",
"Skaitmantas Puslapinis"
]

initial_book_years = [
1990, 1991, 1992, 1993, 1994, 
1995, 1996, 1997, 1998, 1999,
2000, 2001, 2002, 2003, 2004, 
2005, 2006, 2007, 2008, 2009, 
2010, 2011, 2012, 2013, 2014, 
2015, 2016, 2017, 2018, 2019, 
2020, 2021, 2022, 2023, 2024, 
1899, 1986, 1987, 1988, 1989, 
1989, 1931, 1932, 1993, 1984, 
1991, 1976, 1977, 1978, 1989,
1940, 1949, 1960, 1973, 1984
]

initial_book_genres = [
"Romanas",
"Drama",
"Poetika",
"Trileris",
"Fantastika",
"Nuotykių",
"Biografija",
"Mokslinė fantastika",
"Istorinė literatūra",
"Detektyvas",
"Vaikų literatūra",
"Grožinė literatūra",
"Klasika",
"Pasaka",
"Žurnalistika",
"Kultūros istorija",
"Saviugda",
"Psichologija",
"Filosofija",
"Sociologija",
"Sportas",
"Kelionių literatūra",
"Kulinarija",
"Menas",
"Fotografija",
"Poezija",
"Apsakymas",
"Epocha",
"Metafizika",
"Mokslas",
"Teologija",
"Religija",
"Politika",
"Ekologija",
"Feministinė literatūra",
"Asmeninė istorija",
"Motyvacija",
"Kriminalinė literatūra",
"Satyra",
"Humoras",
"Komiksai",
"Animacija",
"Žurnalų leidyba",
"Filmų scenarijai",
"Literatūros kritikų",
"Literatūros teorija",
"Romanas",
"Romanas",
"Romanas",
"Romanas",
"Romanas"
]

initial_book_quantities = [random.randint(0, 100) for _ in range(50)]


initial_books = [initial_book_names,initial_authors,initial_book_years,initial_book_genres,initial_book_quantities]