import random

initial_readers = ["Katinėlis Pūkuotukas",
"Aš Pats Nesuprantu",
"Pūkuotas Dramblys",
"Šokantis Pyragas",
"Raudonas Bananų Pats",
"Burbulinis Šuo",
"Saldus Sūrio Sūris",
"Džiaugsminga Laužyta Banga",
"Kaimo Tinginys",
"Mėnulio Kepurė",
"Juokingas Varlė",
"Įsikūnijęs Žirafa",
"Nežinomas Krapukas",
"Šokoladinis Tinginys",
"Kiaušinis Balansavimas",
"Slaptoji Pica",
"Skraidantis Batutas",
"Karamelinis Foka",
"Dainuojantis Paukštis",
"Pūkų Svajotojas",
"Tingus Panda",
"Burbuliuojantis Pienas",
"Vytis Vakarėlis",
"Šluota Vajus",
"Palaidinukas Smaližius",
"Pusryčių Miegalius",
"Jautis Su Kepurė",
"Panašus Į Pusryčius",
"Juokingas Kepurinis",
"Šokantis Vyras",
"Pavasarinis Drakonas",
"Sklandus Bananų Ritinys",
"Kreminis Lazdynas",
"Žaismingas Pupeliukas",
"Valgomasis Vėžlys",
"Sūrus Avokadas",
"Įspūdingas Kiškis",
"Juokingas Pilkas Debesėlis",
"Mielas Avinas",
"Šokinėjantis Žirgas",
"Nupieštas Kepurinis",
"Balionų Pasaka",
"Mėlynas Giraffas",
"Akrobatinis Kiaušinis",
"Šventinis Pyragėlis",
"Naktinis Sūriukas",
"Žalias Tinginys",
"Džiugus Džemperis",
"Keistas Moliūgas",
"Saldus Žirafas"]

initial_book_names = [
"Ugnies Žiedas",
"Vėjo Dainos",
"Laiko Sūkuriai",
"Paslaptis",
"Paskutinė Mūza",
"Nakties Sūkurys",
"Šviesos Kelias",
"Dangaus Vaikai",
"Pavasario Pėdsakai",
"Žvaigždžių Kelionė",
"Rudens Pasaka",
"Žalioji Rūta",
"Nekaltoji Meilė",
"Vampyro Vakaras",
"Vėjo Šokis",
"Mirusiųjų Naktis",
"Saldūs Sapnai",
"Dulkių Jūra",
"Nematomas Draugas",
"Naktinė Medžioklė",
"Vandenyno Paslaptys",
"Lauko Giesmė",
"Knygų Šalis",
"Magijos Aidas",
"Dvasios Kova",
"Kalnų Pėdsakai",
"Sparnuota Širdis",
"Saulės Mūša",
"Ledinė Srovė",
"Šešėlių Vakaras",
"Akmenų Pasaka",
"Vilties Keliu",
"Vandens Kelias",
"Širdies Pavasaris",
"Nemirtingas Meilė",
"Senas Draugas",
"Tamsos Pasaka",
"Pavasario Atgimimas",
"Išminties Žodis",
"Kraujas ir Sniegas",
"Skrydžio Tiesa",
"Burtininkų Kova",
"Atgimimo Laikas",
"Bjaurusis Ančiukas",
"Žemės Sūnus",
"Kalbantis Miškas",
"Žvaigždžių Dulkės",
"Dangaus Kelyje",
"Svetimas Žemėje",
"Apsiniaukusi Naktis"
]

initial_authors = [
"Vėjas Švilpukas",
"Ugnė Makaronaitė",
"Laima Linksmauskaitė",
"Žygimantas Čeburekas",
"Kazimieras Juokutis",
"Aistė Krembelytė",
"Mantas Kopūstas",
"Viktoras Perkūnaitis",
"Dainius Traukinis",
"Ieva Plepytė",
"Romas Vėplinas",
"Giedrė Vafliukė",
"Danutė Blynienė",
"Jokūbas Nesąmonaitis",
"Vilma Traukaitė",
"Arūnas Juokalius",
"Kotryna Pupikė",
"Valdas Trolis",
"Inga Džiaugsmuolė",
"Simonas Drimblys",
"Neringa Sūrelienė",
"Darius Baravykas",
"Justas Piešimas",
"Gintarė Kalbėtoja",
"Jolanta Rimtutė",
"Aurelijus Trūdelis",
"Rūta Pūkuotukė",
"Vaidotas Pramiegautas",
"Miglė Svirplytė",
"Saulius Užsimiegojęs",
"Gabrielė Pamestinukė",
"Andrius Uodega",
"Julija Vėjelienė",
"Vytautas Kulšytis",
"Rasa Kalendrolytė",
"Raimundas Kabliukas",
"Marija Keksienė",
"Martynas Keberiokštas",
"Simona Čirvinas",
"Kęstutis Greitkelis",
"Neringa Kukainytė",
"Tomas Pėdukas",
"Dainius Sūriuvas",
"Agnė Juokutė",
"Vytas Ledainis",
"Kristina Plepytė",
"Darius Kraputis",
"Mantas Smigruolis",
"Evelina Viščiukienė",
"Vėjas Purvynėlis",
"Skaitmantas Knopkaitis"
]

initial_book_years = [
1990, 1991, 1992, 1993, 1994, 
1995, 1996, 1997, 1998, 1999,
2000, 2001, 2002, 2003, 2004, 
2005, 2006, 2007, 2008, 2009, 
2010, 2011, 2012, 2013, 2014, 
2015, 2016, 2017, 2018, 2019, 
2020, 2021, 2022, 2023, 2024, 
1899, 1986, 1987, 1988, 1989, 
1989, 1931, 1932, 1993, 1984, 
1991, 1976, 1977, 1978, 1989,
1940, 1949, 1960, 1973, 1984
]

initial_book_genres = [
"Romanas",
"Drama",
"Poetika",
"Trileris",
"Fantastika",
"Nuotykių",
"Biografija",
"Mokslinė fantastika",
"Istorinė literatūra",
"Detektyvas",
"Vaikų literatūra",
"Grožinė literatūra",
"Klasika",
"Pasaka",
"Žurnalistika",
"Kultūros istorija",
"Saviugda",
"Psichologija",
"Filosofija",
"Sociologija",
"Sportas",
"Kelionių literatūra",
"Kulinarija",
"Menas",
"Fotografija",
"Poezija",
"Apsakymas",
"Epocha",
"Metafizika",
"Mokslas",
"Teologija",
"Religija",
"Politika",
"Ekologija",
"Feministinė literatūra",
"Asmeninė istorija",
"Motyvacija",
"Kriminalinė literatūra",
"Satyra",
"Humoras",
"Komiksai",
"Animacija",
"Žurnalų leidyba",
"Filmų scenarijai",
"Literatūros kritikų",
"Literatūros teorija",
"Romanas",
"Romanas",
"Romanas",
"Romanas",
"Romanas"
]

initial_book_quantities = [random.randint(0, 100) for _ in range(50)]


initial_books = [initial_book_names,initial_authors,initial_book_years,initial_book_genres,initial_book_quantities]